### ISSUE TITLE
Local transformation and internal SVG element access - Element Box attributes

### ISSUE THREAD

**Issue by rossanoparis** [sammycage/lunasvg#164]
### Data
This issue refers to: [issue 98](https://github.com/sammycage/lunasvg/issues/98)
Library version: v2.3.9 (master)
Testing SVG file: [groups.svg.zip](https://github.com/sammycage/lunasvg/files/14975895/groups.svg.zip)

| Document    | Details | InkScape SVG Properties |
| -------- | ------- | ------- |
| ![image](https://github.com/sammycage/lunasvg/assets/33904565/6b0cbcdf-746e-4c9a-945c-ebe3ffb46495) | unit: **px**<br><br>**document**<br>W: 163 H: 288<br>Top left (0, 0)<br>Bottom rigth (163, 288)<br>Center (81.5, 144)<br><br>**g1 (group 1)**<br>  W: 163 H: 108<br>B1 (0, 0)<br>Bottom rigth (163, 108)<br>C1 (81.5, 54)<br><br>**g2 (group 2)**<br>  W: 108 H: 112<br>B2 (49, 176)<br>Bottom rigth (157, 288)<br>C2 (103, 232) | ![image](https://github.com/sammycage/lunasvg/assets/33904565/25ef32b8-c51a-4576-8123-6890d6edce33) |

### Scope
I want to get elements size and position from the SVG content

### Testing code
```
// Load document
auto document = Document::loadFromFile(filesvg);
Box dbox(0, 0, document->width(), document->height());

// Retrieve the SVG element - g1
auto elementg1 = document->getElementById("g1");
auto boxg1 = elementg1.getBBox();

// Retrieve the SVG element - g2
auto elementg2 = document->getElementById("g2");
auto boxg2 = elementg2.getBBox();
```
### Results
The following details are wrong compared to the SVG document.

**Element g1 (group 1) details**
boxg1.x = 72
boxg1.y = 39
boxg1.w = 54
boxg1.h = 36
The expected values should be same as **B1**

**Element g2 (group 2) details**
boxg2.x = 84
boxg2.y = 108
boxg2.w = 37
boxg2.h = 39
The expected values should be same as **B2**

### Remarks
Perhaps the library doesn't use the SVG "scale", in this example the scale is 3.0 (see document SVG properties above).
Should the library calculate the scale using the following SVG attributes ?
Even though this doesn't explain values for X and Y
```
<svg
   width="162.61"
   height="287.64658"
   viewBox="0 0 54.203334 95.882195"
```
Scale: 162.61 / 54.203334 = 3

**Comment by sammycage** [comment]
With the latest commit https://github.com/sammycage/lunasvg/commit/17b595a6f1fa10ff5f56a7ab9a7134b511735968, you can now map the local coordinates to absolute coordinates.

```cpp

// Load document
auto document = Document::loadFromFile(filesvg);
Box dbox(0, 0, document->width(), document->height());

// Retrieve the SVG element - g1
auto elementg1 = document->getElementById("g1");
auto boxg1 = elementg1.getBBox().transformed(elementg1.getAbsoluteTransform());

// Retrieve the SVG element - g2
auto elementg2 = document->getElementById("g2");
auto boxg2 = elementg2.getBBox().transformed(elementg2.getAbsoluteTransform());

```

**Comment by rossanoparis** [comment]
I did another test using:
Testing SVG file: [groups.svg.zip](https://github.com/sammycage/lunasvg/files/14975895/groups.svg.zip)
It seems that something wrong is still present
Applying the code below using the two groups, g1 and g2, produces different results.

### Element g1 (group 1)

**InkScape details**
![image](https://github.com/sammycage/lunasvg/assets/33904565/7ceb1f9f-18ef-4dec-a05a-923b9cff9cd7)

Values from code `auto boxg1 = elementg1.getBBox().transformed(elementg1.getAbsoluteTransform());`
**X**: 0px **Y**: 0px **W**: 162,61px **H**: 108,36px
They are OK


### Element g2 (group 2)

**InkScape details**
![image](https://github.com/sammycage/lunasvg/assets/33904565/286886cb-7079-4591-8b1d-90547950376c)

Values from code `auto boxg2 = elementg2.getBBox().transformed(elementg2.getAbsoluteTransform());`
**X**: 48.28px **Y**: 171.44px **W**: 112.25px **H**: 117,79px
They are not OK

**Comment by sammycage** [comment]
This line of code, `element.getBBox().transformed(element.getAbsoluteTransform()),` returns a `Box` object that provides information about the size of an element and its position relative to the `viewport.`

Example:

In this simple example, the code retrieves the `Box` object representing the bounding client rectangle of respective elements and renders their outlines.

```cpp

int main(int argc, char** argv)
{
    // Load document
    auto document = Document::loadFromFile("/home/sammycage/Projects/groups.svg");
    Box dbox(0, 0, document->width(), document->height());

    // Retrieve the SVG element - g1
    auto elementg1 = document->getElementById("g1");
    auto boxg1 = elementg1.getBBox().transformed(elementg1.getAbsoluteTransform());

    // Retrieve the SVG element - g2
    auto elementg2 = document->getElementById("g2");
    auto boxg2 = elementg2.getBBox().transformed(elementg2.getAbsoluteTransform());

    // Retrieve the SVG element - path1
    auto elementpath1 = document->getElementById("path1");
    auto boxpath1 = elementpath1.getBBox().transformed(elementpath1.getAbsoluteTransform());

    // Retrieve the SVG element - path2
    auto elementpath2 = document->getElementById("path2");
    auto boxpath2 = elementpath2.getBBox().transformed(elementpath2.getAbsoluteTransform());

    // Retrieve the SVG element - path3
    auto elementpath3 = document->getElementById("path3");
    auto boxpath3 = elementpath3.getBBox().transformed(elementpath3.getAbsoluteTransform());

    // Retrieve the SVG element - path4
    auto elementpath4 = document->getElementById("path4");
    auto boxpath4 = elementpath4.getBBox().transformed(elementpath4.getAbsoluteTransform());

    auto bitmap = document->renderToBitmap(0, 0, 0xFFFFFFFF);
    plutovg_surface_t* surface = plutovg_surface_create_for_data(bitmap.data(), bitmap.width(), bitmap.height(), bitmap.stride());
    plutovg_t* pluto = plutovg_create(surface);

    const double dash[] = {3, 3};

    plutovg_set_rgb(pluto, 0, 0, 1);
    plutovg_set_dash(pluto, 0, dash, 2);

    // Draw outline around element "g1"
    plutovg_rect(pluto, boxg1.x, boxg1.y, boxg1.w, boxg1.h);
    plutovg_stroke(pluto);

    // Draw outline around element "g2"
    plutovg_rect(pluto, boxg2.x, boxg2.y, boxg2.w, boxg2.h);
    plutovg_stroke(pluto);

    // Draw outline around element "path1"
    plutovg_rect(pluto, boxpath1.x, boxpath1.y, boxpath1.w, boxpath1.h);
    plutovg_stroke(pluto);

    // Draw outline around element "path2"
    plutovg_rect(pluto, boxpath2.x, boxpath2.y, boxpath2.w, boxpath2.h);
    plutovg_stroke(pluto);

    // Draw outline around element "path3"
    plutovg_rect(pluto, boxpath3.x, boxpath3.y, boxpath3.w, boxpath3.h);
    plutovg_stroke(pluto);

    // Draw outline around element "path4"
    plutovg_rect(pluto, boxpath4.x, boxpath4.y, boxpath4.w, boxpath4.h);
    plutovg_stroke(pluto);

    plutovg_surface_write_to_png(surface, "outlined.png");

    plutovg_destroy(pluto);
    plutovg_surface_destroy(surface);

    return 0;
}
```

![outlined](https://github.com/sammycage/lunasvg/assets/29164324/dd8b44b1-b64b-440f-8e8e-37c6c857a54f)

**Comment by sammycage** [comment]
@rossanoparis Note: `element.getBBox().transformed(element.getAbsoluteTransform())` is the same as the `element.getBoundingClientRect()` method in JavaScript.

According to ChatGPT,

The `getBoundingClientRect()` method in JavaScript returns the size of an element and its position relative to the viewport. While it aims to provide consistency across browsers, there are several reasons why the values it returns might differ:

1. **Browser Rendering Engine Differences**: Different browsers use different rendering engines (e.g., Blink for Chrome, Gecko for Firefox, WebKit for Safari), which may have slight variations in how they calculate element dimensions and positions.

2. **Viewport Size and Zoom Level**: The viewport size and zoom level can affect how elements are positioned and sized relative to it. Since browsers may interpret viewport size and zoom differently, it can lead to variations in the values returned by `getBoundingClientRect()`.

3. **Subpixel Rendering**: Browsers may use different methods for subpixel rendering, resulting in slight variations in the positioning and sizing of elements, especially for elements with non-integer pixel dimensions.

4. **Browser Extensions and Add-ons**: Browser extensions or add-ons can sometimes modify the behavior of the browser, which might indirectly affect the values returned by `getBoundingClientRect()`.

5. **CSS Resets and User Styles**: CSS resets or user-defined styles applied to elements can alter their default dimensions and positions, leading to inconsistencies across browsers.

6. **Browser Bugs and Implementation Differences**: Despite efforts to standardize browser behavior, there may still be bugs or differences in how `getBoundingClientRect()` is implemented across browsers, especially in edge cases or when dealing with complex CSS layouts.

7. **Hardware Acceleration**: Browsers may use hardware acceleration for rendering, and differences in how this is implemented can lead to variations in rendering and positioning.

8. **Browser Version**: Different versions of the same browser may have different implementations or bugs related to `getBoundingClientRect()` that result in varying results.

To mitigate these differences and ensure consistent behavior across browsers, it's often recommended to test thoroughly and, if necessary, use feature detection and polyfills to handle discrepancies. Additionally, being mindful of edge cases and testing across various browser versions can help identify and address any issues.

**Comment by rossanoparis** [comment]
Thank you @sammycage for your detailed explanation.
It is important for users to consider a certain level of approximation when referencing measurements from Inkscape.

This is an example of using wxWidgets functions to draw red rectangles; I got the same results.
![image](https://github.com/sammycage/lunasvg/assets/33904565/da4a65b9-19df-4494-9483-3b5bb9171381)

Once again, thank you!
