### ISSUE TITLE
Plans for lunasvg v3.0.0 Release

### ISSUE THREAD

**Issue by sammycage** [sammycage/lunasvg#170]
We are thrilled to share our roadmap for lunasvg v3.0.0, focusing on significant enhancements and optimizations:

- Support for `text` and `image` Tags #13 #37 #42 #113
- Implement C API Interface #45 #160
- Switch to Meson Build System #131 #116
- Rename `Box` and `Matrix` to `DomRect` and `DomMatrix,` respectively, with improved encapsulation.
- Use `std::unique_ptr` instead of `std::shared_ptr` in the Bitmap implementation.
- Move to C++17 for enhanced language features and performance improvements.
- Utilize C++17’s `std::string_view` instead of `const char*` for more safe string operations.
- Decrease the number of source files to speed up the compilation process.
- Integrate `plutovg` as a `subproject` #110

Your generous support can help sustain and grow this library. If you find value in it, please consider making a donation. Your contributions make a difference! Donate here: [PayPal](https://www.paypal.me/sammycage).

**Comment by sudoLife** [comment]
Great stuff! Do you have an approximate date for the release?

**Comment by sammycage** [comment]
@sudoLife There is no exact date for the release, but it is expected before October.

**Comment by sammycage** [comment]
@sudoLife Update: Text and image rendering capability has been added to plutovg.

**Comment by sudoLife** [comment]
> @sudoLife Update: Text and image rendering capability has been added to [plutovg.](https://github.com/sammycage/plutovg)

Hey that's cool! Since you're planning to add plutovg as subproject in Luna, does that mean Luna is going to get the same functionality?

**Comment by Jeremy-Boyle** [comment]
Hello, any chance that you could push a update for vcpkg, master currently works for my svg rendering but the latest version does not. 

Thank you !

**Comment by sammycage** [comment]
@Jeremy-Boyle Could you please let me know what specific issues you're encountering with the latest version? I'd like to understand the problem better.

**Comment by Jeremy-Boyle** [comment]
> @Jeremy-Boyle Could you please let me know what specific issues you're encountering with the latest version? I'd like to understand the problem better.

Hi, sorry about not being clearer, the current 2.4.0 release when rendering a document to a bitmap, it displays as black. The current master branch however works perfectly fine. I'm not exactly sure what the specific issue is with 2.4.0. 

I also used the svg_to_png example to verify that it was no issues with my implementation.

**Comment by sammycage** [comment]
@Jeremy-Boyle Hi, thanks for bringing this to my attention. To help me investigate further, could you please share the SVG file you're encountering problems with? That will allow me to better understand what's going on with the 2.4.0 release. I appreciate your help!

**Comment by Jeremy-Boyle** [comment]
Here's an example that doesn't work . 

https://assets.tarkov.dev/maps/svg/Customs-Ground_Level.svg

**Comment by asmwarrior** [comment]
Hi, for the release, here is my suggestion:

1, when I looked at the source code:

https://github.com/sammycage/lunasvg/blob/master/include/lunasvg.h

This header file has many doxygen style comments, but the comments are not documented, I mean it lacks a lot of descriptions. For example, it see many function arguments are list in the comments, but no descriptions.

As a developer, I need to understand those header files, because they are the interface of the whole library, I need to understand how to use this library. I see there is a file: 

https://github.com/sammycage/lunasvg/blob/master/examples/svg2png.cpp

Is this the only "example" file? I think more example file is need, so the user can understand the whole usage of the library.

2, I see a sub folder named "subprojects",  it looks like it points to another project: [sammycage/plutosvg: Tiny SVG rendering library in C](https://github.com/sammycage/plutosvg)

From the project description, lunasvg is a C++ library for rendering svg file, and plutosvg is a C library for rendering svg file, I'm not sure what is their relationship. Do they depends? I mean the former depends on the later one? or verse vice? 

Anyway, thanks for your work!

**Comment by sammycage** [comment]
@asmwarrior Thank you for your feedback and for taking the time to review the project!

1. I appreciate your observation regarding the doxygen comments in `lunasvg.h`. Improving the documentation is important to me, and I’ll be working on adding more detailed descriptions to the function arguments and overall documentation before the release of this version. I also understand the need for more examples, and I plan to include additional example files to help users better understand the library.

2. Regarding the subproject, thank you for pointing that out. Just to clarify, the project in the `subprojects` folder is actually `plutovg`, not `plutosvg`. `PlutoVG` is a 2D vector rendering library similar to Cairo or Skia, and I’m using it as the backend for `lunasvg`. There isn’t a direct dependency between `lunasvg` and `plutosvg` (which is a different library). Each serves distinct purposes within the ecosystem.

Thank you again for your valuable suggestions. I’ll make sure to incorporate them before the release.

**Comment by asmwarrior** [comment]
>     2. Regarding the subproject, thank you for pointing that out. Just to clarify, the project in the `subprojects` folder is actually `plutovg`, not `plutosvg`. `PlutoVG` is a 2D vector rendering library similar to Cairo or Skia, and I’m using it as the backend for `lunasvg`. There isn’t a direct dependency between `lunasvg` and `plutosvg` (which is a different library). Each serves distinct purposes within the ecosystem.

Thanks, indeed `lunasvg` needs `plutovg`, sorry I have made a mistake, those two names(`plutovg` and `plutosvg`) are similar.
