### ISSUE TITLE
Bitmap::valid() reversed in 3.0

### ISSUE THREAD

**Issue by Randalphwa** [sammycage/lunasvg#190]
Previously, I used:

```C++
if ( bmp.valid() )
```

to verify that `Document->render...()` created a valid bitmap. With 3.0, Bitmap::valid() returns false if the bitmap exists whereas previously it returned true. It took me a while to find the problem, and I see that valid() is documented as deprecated but not marked as such. It certainly should not be used in it's current form since the correct check would now be:

```C++
if ( !bmp.valid() )
```

I.e., if valid returns false then the bitmap is valid.

Could this be either reversed back to it's original meaning so it doesn't break existing code, or marked as deprecated so that at least there is a compiler warning when using it?

**Comment by sammycage** [comment]
> Could this be either reversed back to it's original meaning so it doesn't break existing code

I have addressed this issue last week in this [commit](https://github.com/sammycage/lunasvg/commit/2246b6a171bb4e64a20d793861de8f44862fed53). I will release the patch when the time is right.

> It took me a while to find the problem, and I see that valid() is documented as deprecated but not marked as such.

Since the API header is using C++11, I don’t see an easy way to mark the valid() function as [[deprecated]]. Instead, I’ve opted to use Doxygen comment style to indicate its deprecated status.
