### ISSUE TITLE
Problem with edit-undo-sf.svg

### ISSUE THREAD

**Issue by Randalphwa** [sammycage/lunasvg#193]
Screenshot:

![edit-undo-af](https://github.com/user-attachments/assets/0a621e91-bbe6-4baf-a6b5-5d9257877e90)

SVG file:

![Edit-undo-af](https://github.com/user-attachments/assets/b2fd6047-3fb3-4212-b74c-751e9e8375f1)

**Comment by sammycage** [comment]
| Size     | Image                                                                                                             |
|----------|-------------------------------------------------------------------------------------------------------------------|
| `48x48`  | ![edit-undo-sf-48x48](https://github.com/user-attachments/assets/cdd57098-187a-46b6-95d1-f71bd335940b)           |
| `60x60`  | ![edit-undo-sf-60x60](https://github.com/user-attachments/assets/ae35a0b9-aee3-4253-be58-87ea825dd58b)           |
| `128x128`| ![edit-undo-sf svg-128x128](https://github.com/user-attachments/assets/8ea06651-f766-4c24-bd3c-b1d198813e34)     |
| `512x512`| ![edit-undo-sf svg-512x512](https://github.com/user-attachments/assets/0db0c5e1-bc6a-4256-91dd-3e7ce53389d6)     |

Maybe the pixelation is due to an incorrect scale setting when rendering with `svg2png` at various sizes. I don't notice any difference in output quality.

**Comment by Randalphwa** [comment]
My error. The thorvg code converts to wxImage whereas the lunavg and nanovg code converts to wxBitmap. Passing the wxBitmap to wxStaticBitmap::SetBitmap() is apparently scaling the already scaled image, whereas passing wxImage does not. The problem only shows up on a scaled high-resolution display, and would not show up were my test app using lunasvg via the wxBitmapBundle code it will get added to which only scales once.
