### ISSUE TITLE
How to get lunasvg version number?

### ISSUE THREAD

**Issue by vomikan** [sammycage/lunasvg#45]
The About dialog in the [app](https://github.com/moneymanagerex/moneymanagerex/) displays a summary of the products used. How to get lunasvg version number?

```
MMEX is using the following support products:
• wxWidgets 3.1.5 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg 
• libcurl/7.61.1-DEV WinSSL
• gettext 0.21
• apexcharts.js
```

Thanks

**Comment by sammycage** [comment]
The version number can be found here https://github.com/sammycage/lunasvg/blob/6b37cb15f6ab64be7efc3fb9670ce8263216d9a9/CMakeLists.txt#L3 But the problem is how to get it programmatically.

My plan is to implement a class called Environment that will contain all the necessary information such as the `version`,` dpi`, `view Dimensions`, etc

Example

```cpp
static const std::string& Environment::version();
```

**Comment by sammycage** [comment]
The version number can be found here https://github.com/sammycage/lunasvg/blob/6b37cb15f6ab64be7efc3fb9670ce8263216d9a9/CMakeLists.txt#L3 But the problem is how to get it programmatically.

My plan is to implement a class called Environment that will contain all the necessary information such as the `version`,` dpi`, `view Dimensions` etc

Example

```cpp
static const std::string& Environment::version();
```
