### ISSUE TITLE
API for background image

### ISSUE THREAD

**Issue by zcream** [sammycage/lunasvg#60]
Using `Bitmap(std::uint8_t* data, std::uint32_t width, std::uint32_t height, std::uint32_t stride);` one can supply a custom buffer with a background image.

However, both `render` and `renderToBitmap` have a background color. Does this mean that lunasvg will always overwrite the custom background?

**Comment by fdwr** [comment]
@zcream I had the same experience. I'm rendering multiple SVG icons into an existing atlas texture to draw toolbar and menu icons for arbitrary DPI's, and there's no need for the background pixels to be cleared because I already did that anyway. Additionally the atlas texture bitmap pixels passed into `render()` are BGRA premultiplied so that I can use them with multiple renderers (SDL, Cairo, GDI, GDI+, Direct3D, OpenGL) which either require or at least work most efficiently with premultiplied textures. So lunasvg undoing plutovg's canvas output is counterproductive here.

**Comment by sammycage** [comment]
#73

**Comment by sammycage** [comment]
You can now use one image buffer to render multiple images @fdwr @zcream

Example : 

```cpp

auto document = Document::loadFromFile("tiger.svg");

const int tileW = 300;
const int tileH = 300;

Bitmap bitmap(900, 900);
bitmap.clear(0xF0FFF0FF); // HoneyDew
for(int y = 0;y < bitmap.height();y += tileH)
{
    for(int x = 0;x < bitmap.width();x += tileW)
    {
        Matrix matrix(tileW / document->width(), 0, 0, tileH / document->height(), x, y);
        document->render(bitmap, matrix);
    }
}

bitmap.convertToRGBA();

stbi_write_png("tiledtiger.png", bitmap.width(), bitmap.height(), 4, bitmap.data(), 0);
```

tiledtiger.png :

![tiledtiger](https://user-images.githubusercontent.com/29164324/155888411-14dbfb83-8001-4862-9ecd-1d146ea32b7e.png)
